version: "3.3"
networks:
  jenkins_swarm:
volumes:
    jenkins_data: {}
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8443:8443
      - 50000:50000
    restart: always
    networks:
      - jenkins_swarm
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 2
      # resources:
      # reservations:
      #  cpus: "2"
      #  memory: "2048M"
      restart_policy:
         condition: on-failure
      placement:
        constraints:
          - node.labels.role == worker1
